### ISSUE TITLE
Error response from init causes Logger to crash

### ISSUE THREAD

**Issue by sdball** [smpallen99/syslog#12]
With syslog integrated and configured my application fails to boot. It _looks_ like the error response from init is not playing nicely with Logger:

```
** (Mix) Could not start application logger: Logger.App.start(:normal, []) returned an error: shutdown: failed to start child: Logger.Watcher
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:undef, [{Logger.Backends.Syslog, :init, [Logger.Backends.Syslog], []}, {GenEvent, :do_handler, 3, [file: 'lib/gen_event.ex', line: 1101]}, {GenEvent, :do_add_handler, 5, [file: 'lib/gen_event.ex', line: 1058]}, {GenEvent, :handle_msg, 5, [file: 'lib/gen_event.ex', line: 726]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
```

In init it looks like an error is returned unless there is a registered process called `:user` but I don't see any code that would make it or docs detailing what it's expected to be.

My configuration is:

```elixir
config :logger,
  # compile_time_purge_level: :error,
  level: :debug,
  utc_log: true,
  handle_otp_reports: true,
  handle_sasl_reports: true,
  backends: [Logger.Backends.Syslog],
  syslog: [facility: :local1, appid: "myapp", host: "build", port: 514]
```

**Comment by smpallen99** [comment]
try setting :host like this: `host: '127.0.0.1'`

Also, did you put :syslog in your `applications` function in `mix.exs`?

Steve

**Comment by sdball** [comment]
Aha! I had a couple things wrong.

- Your project is not the same syslog project that's on hex.pm. Oops! When I fixed that the init error was no problem 😊 
- You're right, `"build"` as a hostname did not work, but `'build'` does. Thanks!
